### PR TITLE
Fixes to make linux variant a proper executable.

### PR DESCRIPTION
**Pull request by aurelijusrozenas**

### CODE REVIEW

**Comment by james-nesbitt** [comment]
your patch just adds 

`#!/usr/bin/env python`

But your PR completely reformats the whitespace of the file.

**Comment by vmitchell85** [comment]
I agree with @james-nesbitt - I'd rather not change the whitespace or line endings of the one file and ignore the rest. I'll look into this a bit more...

**Comment by vmitchell85** [comment]
Added shebang manually: See commit 0596415

**Comment by aurelijusrozenas** [comment]
cha. Just updated my branch :) The file mode must also be changed. Should I make new pull request?

**Comment by aurelijusrozenas** [comment]
About the whitespace:
 - no trailing spaces seems logical to me, but it's just preference;
 - new line at the end of file is considered good practice because it allows to display file diff correctly if new content was added to end of file;
 - windows to unix newlines - to tell the truth, I cannot remember why I did if I did it :)

**Comment by vmitchell85** [comment]
- Newline - sure, I thought one was there
- trailing spaces - seems to be only on line 91
- newlines - I think I originally committed it on a windows machine... only an editor will care, and the good ones will be fine with it right?

Doesn't seem like enough to make a difference... I'll remove the whitespace on 91 and add a newline a the end...

**Comment by aurelijusrozenas** [comment]
OK, windows newlines (`\r`) are a problem. It does not work in linux when I try to run it. Just tried master branch on my machine, got error: 
> /usr/bin/env: „python\r“: File or folder does not exist

**Comment by aurelijusrozenas** [comment]
Same for the files mode as I said earlier. Now you have to run `chmod +x luxafor-linux.py` before it can be ran.

**Comment by aurelijusrozenas** [comment]
Created https://github.com/vmitchell85/luxafor-python/pull/4
Tested all my changes one by one and everything was right from the start.

**Pull request closed without merging**
